### ISSUE TITLE
ENH: Link Github repo to external homepage - brownsnoteboard.com

### ISSUE THREAD

**Issue by tastatham** [geogbristol/brownsnoteboard#4]
Thank you for putting this together. I think this is a great first step in creating a centralised browns note board.

This repository is great for inputting PGR related information but GitHub is not accessible to *everyone*. Not everyone uses or wants to use GitHub. Furthermore, markdown files have poor readability unless they are supported with html/CSS.

To overcome these limitations, an enhancement could be **to link this repository to an external site** such as *brownsnoteboard.com* (or even more simply, github.io).

Otherwise I feel this repository will just become another medium.

**Comment by tastatham** [comment]
@lenkahas fixed this issue by creating geogbrowns.info

**Comment by lenkahas** [comment]
Thank you for comments :)
